name: patrol_tutorial_prep
description: 'A new Flutter project.'
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.4.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_local_notifications: ^17.2.3
  flutter_svg: ^2.0.10+1
  flutter_timezone: ^3.0.1
  permission_handler: ^11.3.1
  timezone: ^0.9.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  patrol: ^3.11.1

flutter:
  uses-material-design: true
  assets:
    - assets/icon/
    - assets/image/

patrol:
  app_name: Patrol Tutorial Prep
  android:
    package_name: com.resocoder.patrol_tutorial_prep
  ios:
    bundle_id: com.resocoder.patrolTutorialPrep
